[package]
name = "BaptswapV2"
version = "1.0.0"
authors = []

[addresses]

bapt_framework = "0x54ec91ebea0561c03441e02d1d6ee9e0a48a4cd742647bb96002c359d5152d01"
baptswap_v2 = "93929b1d6fb9f6b6858a3a816bd8eaed1de5b44e507a1cfcd7761c12a509ab4a"
dev_2 = "97c8aca6082f2ef7a0046c72eb81ebf203ca23086baf15557579570c86a89fd3"

alice = "0x123"
bob = "0x456"

[dev-addresses]


[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dependencies.BaptSwap]
local = "./packages/BaptSwap"

[dependencies.CoinDeployer]
local = "./packages/CoinDeployer"

[dev-dependencies]
