[package]
name = "BaptswapV2"
version = "1.0.0"
authors = []

[addresses]
baptswap_v2 = "91a65207f3a8ac7447da7efe3fd640ef6eaf8f68fcf07f6bec489b89fbef2cd6"
dev_2 = "4dfbdb89ec2e6f9cf082df0fc8b4b95b0d9b4406a686b8f39bfd39ef1bb030e6"

admin = "91a65207f3a8ac7447da7efe3fd640ef6eaf8f68fcf07f6bec489b89fbef2cd6"
treasury = "91a65207f3a8ac7447da7efe3fd640ef6eaf8f68fcf07f6bec489b89fbef2cd6"

alice = "0x123"
bob = "0x456"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "main"
subdir = "aptos-move/framework/aptos-framework"

[dependencies.BaptSwap]
local = "./BaptSwap"

[dependencies.CoinDeployer]
local = "./CoinDeployer"

[dev-dependencies]
