[package]
name = "BaptswapV2"
version = "1.0.0"
authors = []

[addresses]

bapt_framework = "0x54ec91ebea0561c03441e02d1d6ee9e0a48a4cd742647bb96002c359d5152d01"
baptswap_v2 = "4ee0b37ec67bb47e8d5acf469c5282b93a78145b2ba268782bd7b1e73d411d7c"
dev_2 = "97c8aca6082f2ef7a0046c72eb81ebf203ca23086baf15557579570c86a89fd3"

# to be set! testing only
treasury = "0x438f261f7d74f1b04d3558165b0c91df8caa623f5adb8e3dc6427f8c145fbbbb"

alice = "0x123"
bob = "0x456"

[dev-addresses]


[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dependencies.BaptSwap]
local = "./packages/BaptSwap"

[dependencies.CoinDeployer]
local = "./packages/CoinDeployer"

[dev-dependencies]
