[package]
name = "BaptswapV2"
version = "1.0.0"
authors = []

[addresses]
baptswap_v2 = "6ee5ff12d9af89de4cb9f127bc4c484d26acda56c03536b5e3792eac94da0a36"
bapt_framework = "d0ec361a55b327913690b2851cec05f1e017ec6c647689cae051644f667a1ddb"
dev_2 = "438f261f7d74f1b04d3558165b0c91df8caa623f5adb8e3dc6427f8c145fbbbb"

admin = "6dc7c3b14905bff00bd58cce4b140b86f2bf4814bd72e8c95caec370ed5fe41c"
treasury = "6dc7c3b14905bff00bd58cce4b140b86f2bf4814bd72e8c95caec370ed5fe41c"

alice = "0x123"
bob = "0x456"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dependencies.BaptSwap]
local = "../BaptSwap"

[dependencies.CoinDeployer]
local = "../CoinDeployer"

[dev-dependencies]
